import type { Expression } from './types';

// Direct imports from lottie-emojis — 152 available animations
import {
  Beam,
  Happy,
  Smile,
  Sad,
  Cry,
  Angry,
  Scold,
  Fearful,
  Screaming,
  Surprise,
  Astonished,
  MindBlown,
  Confused,
  Thinking,
  RollingEyes,
  SideEye,
  Smirking,
  Smug,
  Zany,
  Cool,
  StarEye,
  Wink,
  Grinning,
  Relief,
  Relieved,
  Expressionless,
  Worried,
  Anxious,
  ThumbsUp,
  Rocket,
  Fire,
  ConfettiBall,
  Fireworks,
  Salute,
  Wave,
  Victory,
  BrokenHeart,
  Hearts,
  GlowingStar,
  Correct,
  Wrong,
  Exclamation,
  Sleeping,
  Sleepy,
  Yawning,
  Shushing,
  Flushed,
  Sweat,
  Gratitude,
  TearsOfJoy,
  Melted,
  Disguised,
  Concern,
  Halo,
  Graduate,
  DirectHit,
} from 'lottie-emojis';

type LottieData = unknown;

export const EXPRESSION_LOTTIE_MAP: Record<Expression, LottieData> = {
  neutral: Smile,
  happy: Happy,
  sad: Sad,
  angry: Angry,
  fear: Fearful,
  surprise: Surprise,
  disgust: Confused,
  thinking: Thinking,
  confused: Confused,
  excited: StarEye,
  sleepy: Sleeping,
  love: Hearts,
  annoyed: Scold,
  shy: Flushed,
  proud: Cool,
  bored: Expressionless,
  nervous: Anxious,
  curious: SideEye,
  suspicious: RollingEyes,
  relieved: Relieved,
  ready: ThumbsUp,
  processing: Thinking,
  listening: Smirking,
  speaking: Grinning,
  error: Wrong,
  greeting: Wave,
  winking: Wink,
  celebrating: ConfettiBall,
  smirking: Smirking,
  wave_goodbye: Wave,
  awkward: Sweat,
  determined: DirectHit,
  hopeful: Gratitude,
  grateful: Gratitude,
  daydreaming: Melted,
  alert: Exclamation,
};

export function getLottieData(expression: Expression): LottieData | null {
  return EXPRESSION_LOTTIE_MAP[expression] ?? null;
}

export function getAnimationName(expression: Expression): string {
  return expression;
}
